### ISSUE TITLE
Calculate FECO

### ISSUE THREAD

**Issue by oxicottin** [jkingsman/Canna-Calc#33]
First thank you for the calculator! Sorry I didn't know where to post if this is wrong.... The issue is how do you calculate FECO using your calculator? Lets say I have green dragon tincture and it tested to be 11.5% THC  and I wanted to make FECO with that so I evaporated the alcohol and am left with 8ml of FECO in a syringe. Now lets say I wanted to make 72 1tsp gummies with that 8ml FECO, how many MG will each gummy be? Does your calculator do this calculations?

Thanks,

**Comment by jkingsman** [comment]
Hey there -- unfortunately, there's not really a calculator that can do what you're asking without more information; it's not so much an issue with FECO or edible dosing specifically as it is with not having enough measurements in this scenario.

To determine amount per serving, you've got to know total amount, and to know total amount, you need to know both potency (%) and amount (mg or mL). Knowing percentage potency without knowing the amount of the substance makes it impossible to figure out the actual amount of THC in the substance: 11.5% potency is meaningless if you don't know how much the original is in terms of weight or volume (e.g. 11.5% of 50g of green dragon is 5.75g THC, which is very different from 11.5% of 20g of green dragon which is 2.3g). So, you'd either need to know how much solvent was in the green dragon before evaporation (you already know the percentage potency, so knowing the amount makes it work) or you'd need to assay your FECO (you already know the amount, so know the new percentage potency makes it work).

Once you have a potency and amount for either (which will give equivalent THC amounts, assuming that evaporation didn't cause any THC to break down), you can use the `Oil/Butter Potency` calculator under the heading `mg/Serving` which will tell you what you're looking for. But you need both the  `Product Amount` and `Product Potency` for one form or the other to make it work. Sorry!

**Comment by oxicottin** [comment]
Before evaporation I had 1.5 cups Green Dragon and tested potency using a
tcheck and got 11.5% and i do believe thats per teaspoon.

Im sorry to bother you with this but I just want to get my dosing correct
and not be crippled.

Thanks,
Chad

**Comment by oxicottin** [comment]
Also, I used 28g flower and 1.5 cups Everclear

**Comment by jkingsman** [comment]
Sorry, this is getting a little bit more in depth than I'm comfortable discussing on a public platform. It sounds like you've got all the information you need to successfully use the Oil/Butter Potency calculator; I would suggest learning a bit about percentage to total calculations to help you figure out the numbers you'll need to use that for your purposes.
